const List<Map<String, String>> kExcelAccessFeatures = [
  {"key": "p5m", "label": "Export Excel P5M"},
  {"key": "lpi", "label": "Export Excel LPI"},
  {"key": "hazard", "label": "Export Excel Hazard"},
  {"key": "inspeksi_chp", "label": "Export Excel Inspeksi CHP"},
  {
    "key": "inspeksi_fasilitas_bbm",
    "label": "Export Excel Inspeksi Fasilitas BBM",
  },
  {
    "key": "inspeksi_jalan_tambang",
    "label": "Export Excel Inspeksi Jalan Tambang",
  },
  {"key": "inspeksi_kantor", "label": "Export Excel Inspeksi Kantor"},
  {
    "key": "inspeksi_mtd",
    "label": "Export Excel Inspeksi Mess Toilet dan Dapur",
  },
  {"key": "inspeksi_plant", "label": "Export Excel Inspeksi Plant"},
  {"key": "p2h_bus", "label": "Export Excel P2H Bus"},
  {"key": "p2h_dt", "label": "Export Excel P2H Dump Truck"},
  {"key": "p2h_exca", "label": "Export Excel P2H Excavator"},
  {"key": "p2h_grader", "label": "Export Excel P2H Grader"},
  {"key": "p2h_towerlamp", "label": "Export Excel P2H Tower Lamp"},
  {"key": "p2h_crane", "label": "Export Excel P2H Crane"},
  {"key": "p2h_compactor", "label": "Export Excel P2H Compactor"},
  {"key": "p2h_dozer", "label": "Export Excel P2H Dozer"},
  {"key": "p2h_forklift", "label": "Export Excel P2H Forklift"},
  {"key": "p2h_fuel_truck", "label": "Export Excel P2H Fuel Truck"},
  {"key": "p2h_lv", "label": "Export Excel P2H LV"},
  {"key": "p2h_service_truck", "label": "Export Excel P2H Service Truck"},
  {"key": "p2h_truck", "label": "Export Excel P2H Truck"},
  {"key": "p2h_water_truck", "label": "Export Excel P2H Water Truck"},
  {"key": "p2h_water_pump", "label": "Export Excel P2H Water Pump"},
  {"key": "p2h_wheelloader", "label": "Export Excel P2H Wheel Loader"},
  {"key": "daily_plan", "label": "Export Excel Daily Plan"},
  {"key": "buletin", "label": "Export Excel Buletin"},
];
