// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCkl3448OAzXsnDM3P3pwcdneL4jFseRA',
    appId: '1:183172446233:web:4329daf7627f87284a1288',
    messagingSenderId: '183172446233',
    projectId: 'safety-apps-1717',
    authDomain: 'safety-apps-1717.firebaseapp.com',
    storageBucket: 'safety-apps-1717.firebasestorage.app',
    measurementId: 'G-FF8YC93ZR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPAWEZ05EvLcJ-g36jrtrZbnTukMMgrl0',
    appId: '1:183172446233:android:922bdb1200014f794a1288',
    messagingSenderId: '183172446233',
    projectId: 'safety-apps-1717',
    storageBucket: 'safety-apps-1717.firebasestorage.app',
  );
}
